name:                jimscript
version:             0.1.0.0
github:              "githubuser/jimscript"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/githubuser/jimscript#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  jimscript:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - unix
